package com.winsupply.mdmcustomertoecomsubscriber.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.Setter;

/**
 * Contact Entity
 *
 * @author Ankit Jain
 *
 */
@Entity
@Table(name = "contact", schema = "ecom")
@Getter
@Setter
public class Contact {

    @Id
    @Column(name = "contact_ecm_id", length = 15)
    private String contactECMId;

    @Column(name = "login", length = 80, nullable = false)
    private String login;

    @Column(name = "first_name", length = 60)
    private String firstName;

    @Column(name = "last_name", length = 60)
    private String lastName;

    @Column(name = "contact_email", length = 80)
    private String email;

    @Column(name = "auto_generated_password")
    private boolean autoGeneratedPassword;

    @Column(name = "registration_date")
    private LocalDateTime registrationDate;

    @Column(name = "is_user_confirmed")
    private boolean isUserConfirmed;

    @Column(name = "user_creation_flow", precision = 1)
    private Double userCreationFlow;

    @Column(name = "login_attempt", precision = 1)
    private Double loginAttempt;

    @Column(name = "ecm_active")
    private short ecmActive;

    @Column(name = "contact_type_id", nullable = false)
    private short contactTypeId;

    @OneToOne
    @JoinColumn(name = "customer_ecm_id", referencedColumnName = "customer_ecm_id", nullable = false)
    private Customer customer;

    @OneToOne
    @JoinColumn(name = "contact_role_id", referencedColumnName = "role_id", nullable = false)
    private ContactRole role;

    @OneToOne
    @JoinColumn(name = "contact_address_id", referencedColumnName = "address_id")
    private Address address;
}
